spring.datasource.username=ironpath_user
spring.datasource.password=CHANGE_ME

spring.mail.username=CHANGE_ME
spring.mail.password=CHANGE_ME

app.mail.from=CHANGE_ME

jwt.secret=CHANGE_ME
app.encryption.key=CHANGE_ME

app.public-base-url=http://IP_LOCALE_DU_PC:8080