ALTER TABLE IF EXISTS body_measurements
    ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE;

ALTER TABLE IF EXISTS body_compositions
    ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE;
