spring.application.name=ironpath-backend

# Serveur
server.address=${SERVER_ADDRESS:0.0.0.0}
server.port=${PORT:8080}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.expiration=${JWT_EXPIRATION_MS:86400000}

# Documentation désactivée par défaut
app.security.public-docs=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Désactive l'utilisateur Spring Security généré automatiquement
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true
management.info.build.enabled=true